### ISSUE TITLE
mail to list (m2l_cron)

### ISSUE THREAD

**Issue by michaeleino** [alb-i986/phplist-plugin-mailtolist#3]
Dear,
Thanks a lot for your effort making this nice plug-in works with phplist 3.x.
The core of this plug-in is the automation it can provide,
So any help getting the m2l_cron.php file to get working...  when I do open it by browser I got a blank page.
I do some edits as commented out these lines:
//  require_once "./admin/defaultconfig.inc";  
//  require_once "./admin/connect.php"; 
//  include_once "./admin/lib.php"; 

It just works now... is those files useless here?? or how they should included !
and for my edit is there any risk ???

Thanks a lot.

**Comment by michaeleino** [comment]
Any updates ? any work around !!?

**Comment by alb-i986** [comment]
Hi michaeleino,
unfortunately I've never worked on the script for cron, in fact it is not even included in this repo.
Also, this project has always been a work in progress..

Anyway, I'll try to help you, as far as I can.
First of all, I'd suggest to [turn on the debug mode of PHP by editing config file, php.ini](http://www.phoca.cz/documents/16-joomla/336-how-to-enable-displaying-php-errors-on-site).
Then, check that you placed the file m2l_cron.php in the correct place, i.e. [in your root './lists/' folder](https://forums.phplist.com/viewtopic.php?t=11495), assuming the information I found by googling are correct.
Also, I don't think it is a problem with mail2list, as those `require`s seem to me to belong to the core of phplist.

Let me know if it helped.
Thanks
